/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/database`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/auth/forgot/pass`; params?: Router.UnknownInputParams; } | { pathname: `/forgot/senha/pass`; params?: Router.UnknownInputParams; } | { pathname: `/reset/menos/redefini`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup/page`; params?: Router.UnknownInputParams; } | { pathname: `/live/life/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/panel/profile/page`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/database`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/forgot/pass`; params?: Router.UnknownOutputParams; } | { pathname: `/forgot/senha/pass`; params?: Router.UnknownOutputParams; } | { pathname: `/reset/menos/redefini`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signup/page`; params?: Router.UnknownOutputParams; } | { pathname: `/live/life/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `/panel/profile/page`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/database${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/auth/forgot/pass${`?${string}` | `#${string}` | ''}` | `/forgot/senha/pass${`?${string}` | `#${string}` | ''}` | `/reset/menos/redefini${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/signup/page${`?${string}` | `#${string}` | ''}` | `/live/life/perfil${`?${string}` | `#${string}` | ''}` | `/panel/profile/page${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/database`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/auth/forgot/pass`; params?: Router.UnknownInputParams; } | { pathname: `/forgot/senha/pass`; params?: Router.UnknownInputParams; } | { pathname: `/reset/menos/redefini`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup/page`; params?: Router.UnknownInputParams; } | { pathname: `/live/life/perfil`; params?: Router.UnknownInputParams; } | { pathname: `/panel/profile/page`; params?: Router.UnknownInputParams; };
    }
  }
}
